### ISSUE TITLE
Add a 'reading' partial

### ISSUE THREAD

**Issue by evanplaice** [fluentdesk/fluent-themes#33]
`reading` has no template partial.

``` json
  "reading": [
    {
      "title": "",
      "flavor": "",
      "url": "",
      "author": ""
    }
  ]
```

**Comment by hacksalot** [comment]
Yes, following the spirit of the StackOverflow Careers / Stack Careers "reading" section which, AFAIK, was the first major site to highlight "reading" as potentially important to at least technical employers. Still an edge case, but it should be supported for every FRESH theme.

**Comment by evanplaice** [comment]
The way I look at it. I'm going to post the long form of the resume on my personal website. So every section specified on resume.json will be shown there.

Then the copies that I give to prospective employers will use a copy that contains a relevant subset. I think reading is a very good subject to include.

Who knows. If this matches StackOverflowCareers close enough, they may consider allowing it as an import format in the future.

**Comment by hacksalot** [comment]
Preliminary version added to 0.14.0 (forthcoming).
