### ISSUE TITLE
Add an 'interests' partial

### ISSUE THREAD

**Issue by evanplaice** [fluentdesk/fluent-themes#36]
`interests` has no partial.

``` json
  "interests": [
    {
      "name": "",
      "summary": "",
      "keywords": [
        ""
      ]
    }
  ]
```

**Comment by hacksalot** [comment]
Agreed. This was originally added to the schema to support lossless round-trip conversion between FRESH/FRESCA and SO, Monster, LinkedIn, JSON Resume, most other major formats & sites that have an `interests` section, but officially, all built-in FRESH themes should support all sections.

**Comment by evanplaice** [comment]
:+1:

**Comment by hacksalot** [comment]
Added in 0.14.0-beta.
